若干优化和bug修改。
talebook/talebook pull request #157
Opened 2022-04-15 09:44 UTC by shentar

2022-04-15 13:11 UTC, talebook requested changes

2022-04-15 13:11 UTC, talebook commented on app/src/pages/admin/imports.vue
> +            var path = "/data/books/uploads";
upload和uploads很容易让用户搞混啊。。。再换个名字吧！

另外，我其实还想着后续搞个选目录的弹窗，让用户自己选

2022-04-15 13:11 UTC, talebook commented on app/src/pages/index.vue
> +            { icon: 'mdi-history',        href:'/recent',    text: '分类导览', },
这两个为啥都改成了分类导览？

2022-04-15 13:11 UTC, talebook commented on app/src/store/index.js
> +    }, /*
你这啥编辑器？连注释都要缩上去。。。

2022-04-15 13:11 UTC, talebook commented on docker/start.sh
> +/var/www/talebook/server.py --syncdb
本来是想着用alembic这个工具管理数据库版本的，但是没搞定social_auth的表。算了，就先用syncdb吧

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/scan.py
> +        path = self.settings["scan_upload_path"]
这里的代码，跟imports.vue里的参数有冲突。

2022-04-15 13:11 UTC, talebook commented on webserver/models.py
> +class IpDownloads(Base, SQLAlchemyMixin):
IP限频功能可以职级在nginx中配置的。不应该在server中实现。

http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

2022-04-15 13:11 UTC, talebook commented on webserver/plugins/meta/baike/api.py
> +        mi.publisher = info.get(u"出版社", plat)
这里要兼容下 出版社/连载平台 两种场景。
info.get("出版社", info.get("连载平台", plat))

2022-04-15 13:11 UTC, talebook commented on webserver/plugins/meta/douban.py
> +        # mi.timestamp = utcnow()
为何要注释掉呢？

2022-04-15 13:11 UTC, talebook commented on Dockerfile
> +    mkdir -p /data/books/uploads  && \
文件名太接近了，容易搞混

2022-04-15 13:11 UTC, talebook commented on app/src/pages/admin/imports.vue
> +            var path = "/data/books/uploads";
如果是改为后台参数的话，这里就不用传递这个参数了

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/base.py
> +        items.sort(key=keyg)
这里为何删除了 reverse 参数？

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/base.py
> +    def check_and_increase_download_count(self):
改为NGINX配置即可。但是否要作为默认功能开启？值得再斟酌下

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/base.py
> -        self.do_sort(items, "title", True)
默认按ID排序，我觉得在用户体验上并不好，因为在web上看不出来id究竟是个怎样的次序（因为没展示修改时间）。所以，一般情况下，以title作为排序，让用户体验下会更加直观一些，翻页时甚至能“猜”到第几页是什么字母的书籍。

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/book.py
> +        global books
这里为什么要用global作用域？

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/book.py
> +                                and (tag != "C" and tag != "c" and tag != u"性"):
Cc性，魔术列表？起个有意义的名字定义到外面吧，不然看不懂

2022-04-15 13:11 UTC, talebook commented on webserver/handlers/book.py
> +            if not CONF["ALLOW_GUEST_DOWNLOAD"] and not self.current_user:
函数开头就有这个判断。为何要再写一遍？

2022-04-15 13:33 UTC, shentar commented on webserver/handlers/scan.py
> +        path = self.settings["scan_upload_path"]
嗯，这个就没大改，从前台选取确实更好啊。我把这个先剥离出去吧。不作参数了。你后面补成前台浏览选取的方式。

2022-04-15 13:34 UTC, shentar commented on webserver/handlers/base.py
> +    def check_and_increase_download_count(self):
可以做成选择功能，考虑好了再上吧，做成了默认限制了 ^_^

2022-04-15 13:35 UTC, shentar commented on webserver/handlers/book.py
> +        global books
好像是有个bug，很边角的一个bug，忘记了。。

2022-04-15 13:36 UTC, shentar commented on webserver/handlers/book.py
> +                                and (tag != "C" and tag != "c" and tag != u"性"):
因为单字符被拉去做tag了，误判太多了，就在这硬编码了

2022-04-15 13:39 UTC, shentar commented on webserver/handlers/book.py
> +            if not CONF["ALLOW_GUEST_DOWNLOAD"] and not self.current_user:
拷贝的问题，这一段已经去掉了，不限制单IP下载量的话，不需要了。

2022-04-15 13:41 UTC, shentar commented on webserver/handlers/base.py
> -        self.do_sort(items, "title", True)
我考虑的是按rating + id，所有的排序都在各个接口外部去做了，没法统一在render里面做。这一行是重复了，会导致重复排序。

2022-04-15 13:43 UTC, shentar commented on webserver/handlers/base.py
> +        items.sort(key=keyg)
因为前面的cssortkeygenerator已经带上了order，opdf接口排序不正确的问题就是这里来的。调了很久发现的。

2022-04-15 13:45 UTC, syhily commented
It seems like there is a lot of code format in this PR that may not be accepted. Can we just reformat the code which was truly modified?

2022-04-15 13:47 UTC, syhily commented on docker/start.sh
> +/var/www/talebook/server.py --syncdb
If we use syncdb here. We may better add wait time when we are using talebook with MySQL.

2022-04-15 14:19 UTC, shentar commented on webserver/plugins/meta/douban.py
> +        # mi.timestamp = utcnow()
我感觉导入的时间决定了这本书的加入时间，每次从豆瓣拉一次，这本书就变成了最新的，有点奇怪。就是我前面说的，根据rating + id排序会更好点。这个时间保留也可以。

2022-04-15 14:28 UTC, talebook commented on webserver/plugins/meta/douban.py
> +        # mi.timestamp = utcnow()
图片url中使用了timestamp作为参数，以便在使用cdn时能及时更新。这里最好还是保留timestamp的更新吧。

2022-04-15 14:33 UTC, talebook commented on webserver/handlers/book.py
> +                                and (tag != "C" and tag != "c" and tag != u"性"):
咦，这里的tag是BOOKNAV里预设的，怎么会有单字符的tag出现？

2022-04-15 15:16 UTC, talebook requested changes

2022-04-15 15:16 UTC, talebook commented on webserver/handlers/book.py
> +        global books
看了下，是下面使用books时有个try catch，可能会导致books没有初始化。

这里修改为 `books = []` 即可，辛苦调整下

2022-04-15 15:16 UTC, talebook commented on webserver/plugins/meta/baike/api.py
> +        # mi.timestamp = mi.pubdate
这里也是要把timestamp给开起来

2022-04-16 13:00 UTC, shentar commented on webserver/handlers/book.py
> +                                and (tag != "C" and tag != "c" and tag != u"性"):
我自己用的时候，改了些，我加了这3个tag，我把这个代码调整到自己的commit里面维护。

2022-04-16 13:11 UTC, talebook commented
@shentar   scan目录改为后台配置后，单元测试里的test_scan用例失败了，请修复下，在test_main.py中设置好scan参数的目录。

2022-04-16 16:19 UTC, talebook approved these changes

2022-04-16 16:21 UTC, merged